import assert from "node:assert/strict";
import { dcf, ddm, pe, peg, evEbitda, priceBook, combined } from "../assets/valuation.js";

const company = { currentPrice: 100, freeCashFlow: 1000, cash: 100, debt: 200, sharesOutstanding: 100, forwardEps: 5, eps: 4, epsGrowth: 20, netIncome: 400, dividendPerShare: 2, dividendGrowth: 4, payoutRatio: 40, ebitda: 1200, bookValuePerShare: 30, historicalPE: 20, sectorPE: 22, historicalEvEbitda: 10, sectorEvEbitda: 12, historicalPB: 2, sectorPB: 2.2 };
const dcfInputs = { currentFcf: 1000, growthRate: 8, forecastYears: 5, terminalGrowthRate: 2.5, discountRate: 9, cash: 100, debt: 200, sharesOutstanding: 100 };
const dcfResult = dcf(company, dcfInputs);
assert.ok(dcfResult?.fairValue > 0);
assert.equal(dcf(company, { ...dcfInputs, terminalGrowthRate: 9 }), null);
assert.equal(dcf(company, { ...dcfInputs, sharesOutstanding: 0 }), null);
assert.equal(dcf(company, { ...dcfInputs, currentFcf: -1 }), null);
assert.ok(dcf(company, { ...dcfInputs, cash: 500 }).fairValue > dcfResult.fairValue);
assert.ok(pe(company, { normalizedEps: 5, fairPE: 20 })?.fairValue === 100);
assert.equal(pe({ ...company, eps: -1, forwardEps: -1 }, { normalizedEps: -1, fairPE: 20 }), null);
assert.ok(peg(company, { forwardEps: 5, epsGrowth: 20, targetPeg: 1.2 })?.fairValue === 120);
assert.equal(peg(company, { forwardEps: 5, epsGrowth: 0, targetPeg: 1.2 }), null);
assert.ok(ddm(company, { dividendPerShare: 2, dividendGrowth: 4, requiredReturn: 9 })?.fairValue > 0);
assert.equal(ddm(company, { dividendPerShare: 2, dividendGrowth: 9, requiredReturn: 9 }), null);
assert.ok(evEbitda(company, { ebitda: 1200, fairMultiple: 10, debt: 200, cash: 100, sharesOutstanding: 100 })?.fairValue === 119);
assert.equal(evEbitda(company, { ebitda: -1, fairMultiple: 10, sharesOutstanding: 100 }), null);
assert.ok(priceBook(company, { bookValuePerShare: 30, fairPriceToBook: 2 })?.fairValue === 60);
assert.equal(priceBook(company, { bookValuePerShare: -1, fairPriceToBook: 2 }), null);
const a = pe(company, { normalizedEps: 5, fairPE: 20 }), b = peg(company, { forwardEps: 5, epsGrowth: 20, targetPeg: 1.2 });
assert.ok(combined(company, [a, b])?.fairValue > 0);
assert.equal(combined(company, [{ ...a, confidenceScore: 39 }, b]), null);
console.log("valuation tests passed");
