export const etfs = [
  ["SPY", "S&P 500", "Piață largă"],
  ["RSP", "S&P 500 echiponderat", "Piață largă"],
  ["IWM", "Russell 2000 – companii mici", "Piață largă"],
  ["XLK", "Tehnologia informației", "AI / Tehnologie"],
  ["XLF", "Financiare", "S&P 500 · Financiare"],
  ["XLI", "Industriale", "S&P 500 · Industriale"],
  ["XLY", "Consum discreționar", "S&P 500 · Consum discreționar"],
  ["XLB", "Materiale", "S&P 500 · Materiale"],
  ["XLE", "Energie", "S&P 500 · Energie"],
  ["XLC", "Servicii de comunicații", "S&P 500 · Comunicații"],
  ["XLV", "Sănătate", "S&P 500 · Sănătate"],
  ["XLP", "Consum de bază", "S&P 500 · Consum de bază"],
  ["XLU", "Utilități", "S&P 500 · Utilități"],
  ["XLRE", "Imobiliare / REIT", "S&P 500 · Imobiliare"],
  ["IEF", "Obligațiuni de stat SUA 7–10 ani", "Active defensive"],
  ["HYG", "Obligațiuni corporative high yield", "Active defensive"],
  ["GLD", "Aur fizic", "Active defensive"],
  ["IBIT", "Bitcoin", "Alternative"]
].map(([symbol, name, sector]) => ({ symbol, name, sector }));
