export const etfs = [
  ["SPY", "S&P 500", "Piață largă"],
  ["QQQ", "Nasdaq 100", "Piață largă"],
  ["RSP", "S&P 500 echiponderat", "Piață largă"],
  ["IWM", "Russell 2000 – companii mici", "Piață largă"],
  ["DIA", "Dow Jones 30", "Piață largă"],
  ["SMH", "Semiconductori – mega-cap", "AI / Tehnologie"],
  ["XSD", "Semiconductori – echiponderat", "AI / Tehnologie"],
  ["IGV", "Software", "AI / Tehnologie"],
  ["XLK", "Tehnologia informației", "AI / Tehnologie"],
  ["AIQ", "Inteligență artificială – tematic", "AI / Tehnologie"],
  ["XLF", "Financiare", "Sectoare S&P"],
  ["KRE", "Bănci regionale", "Sectoare S&P"],
  ["XLI", "Industriale", "Sectoare S&P"],
  ["XLY", "Consum discreționar", "Sectoare S&P"],
  ["XLB", "Materiale", "Sectoare S&P"],
  ["XLE", "Energie", "Sectoare S&P"],
  ["XLC", "Servicii de comunicații", "Sectoare S&P"],
  ["XLV", "Sănătate", "Sectoare S&P"],
  ["XLP", "Consum de bază", "Sectoare S&P"],
  ["XLU", "Utilități", "Sectoare S&P"],
  ["XLRE", "Imobiliare / REIT", "Sectoare S&P"],
  ["IWF", "Russell 1000 Growth", "Factori / teme"],
  ["IWD", "Russell 1000 Value", "Factori / teme"],
  ["QUAL", "Factor calitate", "Factori / teme"],
  ["MTUM", "Factor momentum", "Factori / teme"],
  ["GRID", "Rețele electrice și infrastructură energetică", "Factori / teme"],
  ["PAVE", "Infrastructură SUA / capex industrial", "Factori / teme"],
  ["SGOV", "Bonuri de trezorerie 0–3 luni", "Active defensive"],
  ["IEF", "Obligațiuni de stat SUA 7–10 ani", "Active defensive"],
  ["TLT", "Obligațiuni de stat SUA 20+ ani", "Active defensive"],
  ["HYG", "Obligațiuni corporative high yield", "Active defensive"],
  ["GLD", "Aur fizic", "Active defensive"],
  ["IBIT", "Bitcoin", "Alternative"],
  ["VXUS", "Acțiuni globale, exclusiv SUA", "Internațional"],
  ["EEM", "Piețe emergente", "Internațional"]
].map(([symbol, name, sector]) => ({ symbol, name, sector }));
